export const width: string;
export const height: string;
export const hpSlider: string;
export const hpSliderInnerBorderRect: string;
export const hpSliderHandle: string;
export const hpSliderHandleRight: string;
export const hpSliderHandleLeft: string;
export const hpSliderHandleDragBar: string;
export const hpSliderHandlePressed: string;
